version: '2'
services:
  app:
    image: ruby:3.2.1
    environment:
      DATABASE_URL: 'postgresql://user:password@postgres:5432'
    command: bash -c "rm /app/tmp/pids/server.pid ; bundle exec rails server -p 3300 -b 0.0.0.0"
    working_dir: /app
    ports:
      - 3300:3300
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

volumes:
  dbdata:
  bundle:
