default: &default
  adapter: postgresql
  timeout: 5000
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  url: <%= ENV.fetch('DATABASE_URL') %>

development:
  <<: *default
  database: peopleforce_development

test:
  <<: *default
  database: peopleforce_test

production:
  <<: *default
  database: peopleforce
